replace jaeger.servicename with servicename
hypertrace/span-normalizer pull request #19
Opened 2020-09-03 17:19 UTC by dnielsen

Even jaeger would not qualify servicename as jaeger.servicename. So it is more sensible for HT to rename it to serviceName as idiomatically used in the rest of HT.

2020-09-03 18:13 UTC, buchi-busireddy requested changes
@dnielsen We have to do this change in a non-breaking way, making sure all the consumers of this are migrated away from using this attribute first. Otherwise the entity discovery will break.

2020-09-04 00:46 UTC, dnielsen commented
> @buchi-busireddy  👍  for a non-breaking way

2020-09-04 04:10 UTC, kotharironak commented
@anujgoyal1 This change will affect the simulator too. I think we have one option for this.

2020-11-09 04:02 UTC, kotharironak commented
closing this now as it will be taken care of as part of - https://github.com/hypertrace/hypertrace/issues/44

2020-11-09 04:03 UTC, closed without merging